config/routes.rb
Rails.application.routes.draw do
  resources :payment_notifications

  devise_for :profiles, controllers: {
        sessions: 'profiles/sessions'
      }

  root 'tryouts#index'

get 'confirm' => 'tryouts#confirm', as: :tryouts_confirm

resources :tryouts do
  resources :players
end

resources :coaches do
  resources :evaluations
end
  resources :guardianships
  resources :evaluations
  resources :guardians
  resources :coaches
  resources :players

  resources :tryouts do
    member do
get 'confirm' => 'tryouts#confirm'

    end
 end

  resources :tryouts do
    resources :player_tryouts
  end

  resources :player_tryouts do
    resources :players
  end

  resources :player_tryouts

end

app/models/tryout.rb
class Tryout < ActiveRecord::Base
  has_many :player_tryouts
end

app/controllers/tryouts_controller.rb
class TryoutsController < ApplicationController
  before_action :set_tryout , only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_profile!, only: [:index, :show]
  before_action :permissions , except: [:index, :show, :confirm]#[:new, :edit, :create, :update, :destroy]



#GEt /tryouts/confirm
  def confirm
  @player = Player.find(current_profile.id)
  @tryout = Tryout.find(params[:id])
  @player_tryout = @player.player_tryouts.find_by(tryout_id: @tryout.id)

  end


  # GET /tryouts
  # GET /tryouts.json
  def index
    @tryouts = Tryout.all
    #binding.pry
  end

  # GET /tryouts/1
  # GET /tryouts/1.json
  def show
if profile_signed_in? == true

    if current_profile.type == 'Coach'
      @coach  = Coach.find(current_profile.id)
      @tryout.player_tryouts.each do |pt|
        if pt.payment != nil
          if Evaluation.exists?(coach_id: @coach.id, player_tryout_id: pt.id)
            #do nothing
          else
            #always create evaluations if they don't exist
            @evaluation = @coach.evaluations.create(player_tryout_id: pt.id )
          end
        end
      end
    end

  end
  end

  # GET /tryouts/new
  def new
    #redirect_to tryouts_path if current_profile.user.type == "Player"
    @tryout = Tryout.new
  end

  # GET /tryouts/1/edit
  def edit

       #redirect_to tryouts_path if current_profile.user.type == "Player"

  end

  # POST /tryouts
  # POST /tryouts.json
  def create
#redirect_to tryouts_path if current_profile.user.type == "Player"
    @tryout = Tryout.new(tryout_params)

    respond_to do |format|
      if @tryout.save
        format.html { redirect_to @tryout, notice: 'Tryout was successfully created.' }
        format.json { render :show, status: :created, location: @tryout }
      else
        format.html { render :new }
        format.json { render json: @tryout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tryouts/1
  # PATCH/PUT /tryouts/1.json
  def update
#redirect_to tryouts_path if current_profile.user.type == "Player"
    respond_to do |format|
      if @tryout.update(tryout_params)
        format.html { redirect_to @tryout, notice: 'Tryout was successfully updated.' }
        format.json { render :show, status: :ok, location: @tryout }
      else
        format.html { render :edit }
        format.json { render json: @tryout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tryouts/1
  # DELETE /tryouts/1.json
  def destroy
	#redirect_to tryouts_path if current_profile.user.type == "Player"
    @tryout.destroy
    respond_to do |format|
      format.html { redirect_to tryouts_url, notice: 'Tryout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tryout
      @tryout = Tryout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tryout_params
      params.require(:tryout).permit(:date, :fee, :address1, :address2, :city, :state, :zip)
    end

    def permissions
      #binding.pry
	redirect_to tryouts_path if (profile_signed_in? == false) || (current_profile.type != "Coach")
    end

end

app/helpers/tryouts_helper.rb
module TryoutsHelper
end

app/views/tryouts/_form.html.erb
<%= form_for(@tryout) do |f| %>
    <% if @tryout.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@tryout.errors.count, "error") %> prohibited this tryout from being saved:</h2>

          <ul>
            <% @tryout.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="col-md-12">
        <div class="field">
          <%= f.label :date %><br>
          <%= f.datetime_select :date, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="field">
          <%= f.label :fee %><br>
          <%= f.text_field :fee, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :address1 %><br>
          <%= f.text_field :address1, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :address2 %><br>
          <%= f.text_field :address2, class: 'form-control' %>
        </div>
      </div>
      <div class="col-md-6">
        <div></div>
        <div class="field">
          <%= f.label :city %><br>
          <%= f.text_field :city, class: 'form-control' %>
        </div>
        <div class="field">
          <%= f.label :state %><br>
          <%= f.select(:state,
                       ['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 'ID', 'IL',
                        'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI', 'MN', 'MS', 'MO', 'MT', 'NE',
                        'NV', 'NH', 'NJ', 'NM', 'NY', 'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
                        'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], {}, {:class => 'form-control'}) %>
        </div>
        <div class="field">
          <%= f.label :zip %><br>
          <%= f.number_field :zip, class: 'form-control' %>
        </div>
      </div>
    </div>
    <hr>
    <div class="actions">
      <%= f.submit "Submit", class: 'btn btn-primary pull-right' %>
    </div>
<% end %>

app/views/tryouts/confirm.html.erb
<div class="col-md-12">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h3>Confirm Registration</h3>
    </div>
    <div class="panel-body">
      <div class="row">
        <div class="col-md-6">
          <h4><u>Tryout Details</u>:</h4>
          <hr>
          <p>
            <strong>Date:</strong>
            <%= @tryout.date.strftime('%A %d, %Y') + ' - ' + @tryout.date.strftime('%I:%M %P') %>
          </p>

          <p>
            <strong>Fee:</strong>
            $<%= number_with_precision(@tryout.fee, precision: 2) %>
          </p>

          <p>
            <strong>Location:</strong>
            <%= @tryout.address1 %> <%= @tryout.address2 %>, <%= @tryout.city %>
            , <%= @tryout.state %> <%= @tryout.zip %>
          </p>

          <div>
            <iframe
            width="500"
            height="400"
            frameborder="5" style="border:0"
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAdg49Tak1UQabDrP0djPBJlP6Kgp3SG3E
            &q= <%= @tryout.address1 %> <%= @tryout.address2 %> <%= @tryout.city %> <%= @tryout.state %> <%= @tryout.zip %>" allowfullscreen>
            </iframe>
          </div>
        </div>
        <vr>
          <div class="col-md-6">
            <h4><u>Player
              Information</u>: <%= link_to 'Edit', edit_player_path(current_profile.id), class: 'badge pull-right', style: 'color:white' %>
            </h4>
            <hr>
            <p>
              <strong>First Name:</strong>
              <%= @player.first_name %>
            </p>

            <p>
              <strong>Last Name:</strong>
              <%= @player.last_name %>
            </p>


            <p>
              <strong>Email:</strong>
              <%= @player.email %>
            </p>

            <p>
              <strong>Phone:</strong>
              <%= @player.phone %>
            </p>

            <p>
              <strong>Gender:</strong>
              <%= @player.gender %>
            </p>

            <p>
              <strong>Date of Birth:</strong>
              <%= @player.dob.strftime('%A %d, %Y') + ' - ' + @player.dob.strftime('%I:%M %P') %>
            </p>

            <p>
              <strong>Address Line 1:</strong>
              <%= @player.address1 %>
            </p>

            <p>
              <strong>Address Line 2:</strong>
              <%= @player.address2 %>
            </p>

            <p>
              <strong>City:</strong>
              <%= @player.city %>
            </p>

            <p>
              <strong>State:</strong>
              <%= @player.state %>
            </p>

            <p>
              <strong>Zip:</strong>
              <%= @player.zip %>
            </p>

            <p>
              <strong>Experience:</strong>
              <%= @player.experience %>
            </p>
          </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-md-12">
          <%= link_to 'Back', tryouts_path, class: 'btn btn-danger pull-left', style: 'color:white' %>
          <% if @player_tryout == nil || @player_tryout.payment == nil %>
              <%= link_to 'Pay with PayPal', tryout_player_tryouts_path(tryout_id: @tryout.id, player_id: @player.id), method: :post, class: 'btn btn-success pull-right', style: 'color:white' %>
          <% else %>
              <div class="alert alert-danger pull-right">
                <p>You have already registered to this tryout.</p>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tryouts/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Edit Tryout</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
    <%= link_to 'Back', tryouts_path, class: 'btn btn-danger pull-left', style: 'color:white' %>
  </div>
</div>

app/views/tryouts/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Tryouts
      <% if (profile_signed_in? && current_profile.type == 'Coach') %>
          <%= link_to 'New Tryout', new_tryout_path, class: 'pull-right btn btn-success', style: 'color:white' %>
          </h1>
      <% end %>
      </div>
  <div class="panel-body">
    <table class="table table-hover table-striped table-hover">
      <thead>
      <tr>
        <th>Date</th>
        <th>Fee</th>
        <th>Location</th>
        <% if (profile_signed_in? && current_profile.type == 'Coach') %>
            <th colspan="3"></th>
        <% else %>
            <th colspan="1"></th>
        <% end %>
      </tr>
      </thead>

      <tbody>
      <% @tryouts.each do |tryout| %>
          <tr>
            <td><%= link_to tryout.date.strftime('%A %d, %Y') + ' - ' + tryout.date.strftime('%I:%M %P'), tryout %></td>
            <td>$<%= number_with_precision(tryout.fee, precision: 2) %></td>
            <td><%= tryout.address1 %> <%= tryout.address2 %>, <%= tryout.city %> <%= tryout.state %>
              , <%= tryout.zip %></td>
            <td><%= link_to 'Details', tryout, class: 'btn btn-info' %></td>
            <% if (profile_signed_in? && current_profile.type == 'Coach') %>
                <td><%= link_to 'Edit', edit_tryout_path(tryout), class: 'btn btn-default' %></td>
                <td><%= link_to 'Destroy', tryout, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger', style: 'color:white' %></td>
            <% end %>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tryouts/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>New Tryout</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
    <%= link_to 'Back', tryouts_path, class:'btn btn-default pull-left' %>
  </div>
</div>

app/views/tryouts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Tryout Details
      <% if (profile_signed_in? && current_profile.type == 'Coach') %>
          <%= link_to 'Details', edit_tryout_path(@tryout), class: 'btn btn-default pull-right' %>
      <% elsif (profile_signed_in? && current_profile.type == 'Player') %>
          <%= link_to 'Register', new_tryout_player_path(@tryout.id), class: 'btn btn-success pull-right', style: 'color:white' %>
      <% else %>
          <%= link_to 'Register', new_profile_registration_path, class: 'btn btn-success pull-right', style: 'color:white' %>
      <% end %>
      <!--player_tryouts_path(tryout_id: @tryout.id),method: :post-->
    </h1>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-6">
        <div class="col-md-6">
          <h3><strong>Date:</strong></h3>
          <h4><i><%= @tryout.date.strftime('%A %d, %Y') %></i></h4>

          <h3><strong>Time:</strong></h3>
          <h4><i><%= @tryout.date.strftime('%I:%M %P') %></i></h4>

          <h3><strong>Fee:</strong></h3>
          <h4><i>$<%= number_with_precision(@tryout.fee, precision: 2) %></i></h4>
        </div>
        <div class="col-md-6">
          <h3><strong>Address Line 1:</strong></h3>
          <h4><i><%= @tryout.address1 %></i></h4>

          <h3><strong>Address Line 2:</strong></h3>
          <h4><i><%= @tryout.address2 %></i></h4>

          <h3><strong>City:</strong></h3>
          <h4><i><%= @tryout.city %></i></h4>

          <h3><strong>State:</strong></h3>
          <h4><i><%= @tryout.state %></i></h4>

          <h3><strong>ZIP:</strong></h3>
          <h4><i><%= @tryout.zip %></i></h4>
        </div>
      </div>
      <div class="col-md-6">
        <iframe
        width="500"
        height="400"
        frameborder="5" style="border:0"
        src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAdg49Tak1UQabDrP0djPBJlP6Kgp3SG3E
            &q= <%= @tryout.address1 %> <%= @tryout.address2 %> <%= @tryout.city %> <%= @tryout.state %> <%= @tryout.zip %>" allowfullscreen>
        </iframe>
      </div>
    </div>
  </div>
</div>

<% if @coach != nil %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h1>Registered Players</h1>
      </div>
      <div class="panel-body">
        <table class="table table-hover table-striped table-responsive">
          <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Rating</th>
            <th>Speed</th>
            <th>Shooting</th>
            <th>Passing</th>
            <th</th>
          </tr>
          </thead>


          <tbody>


          <% @tryout.player_tryouts.each do |playertryout| %>
              <% if playertryout.payment != nil %>
                  <% @player = Player.find(playertryout.player_id) %>
                  <% @evaluation = @coach.evaluations.find_by(coach_id: @coach.id, player_tryout_id: playertryout.id) %>
                  <tr>
                    <td><%= @player.id %></td>
                    <td><%= link_to @player.first_name.to_s + ' ' + @player.last_name.to_s, players_path %></td>
                    <td><%= @evaluation.rating %></td>
                    <td><%= @evaluation.speed %></td>
                    <td><%= @evaluation.shooting %></td>
                    <td><%= @evaluation.passing %></td>
                    <td><%= link_to 'Evaluation', '#', class:'btn btn-primary pull-right', style:'color:white' %></td>
                  </tr>
              <% end %>
          <% end %>


          </tbody>
        </table>
      </div>
    </div>

<% end %>