config/routes.rb
Rails.application.routes.draw do
  resources :payment_notifications

  devise_for :profiles, controllers: {
        sessions: 'profiles/sessions'
      }

  root 'tryouts#index'

get 'confirm' => 'tryouts#confirm', as: :tryouts_confirm

resources :tryouts do
  resources :players
end

resources :coaches do
  resources :evaluations
end
  resources :guardianships
  resources :evaluations
  resources :guardians
  resources :coaches
  resources :players

  resources :tryouts do
    member do
get 'confirm' => 'tryouts#confirm'

    end
 end

  resources :tryouts do
    resources :player_tryouts
  end

  resources :player_tryouts do
    resources :players
  end

  resources :player_tryouts

end

app/models/player.rb
class Player < Profile
  has_many :player_tryouts#, dependent: :destroy
  has_many :guardianships
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show,:edit, :destroy,:update]
  before_action :permissions, except: [:new]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new

  #  if Player.exists?(:profile_id => current_profile.id)
      #do nothing for now
      @tryout = Tryout.find(params[:tryout_id])
      @player = Player.find(current_profile.id)
      #redirect_to edit_tryout_player_path(@tryout.id, @player.id), notice: 'Player exists'
      redirect_to confirm_tryout_path(@tryout.id), notice: 'Player exists'

  #  else
  #    @player = Player.new
  #    @player.assign_attributes(:profile_id => current_profile.id)
     # @player.save
    #  @tryout = Tryout.find(params[:tryout_id])
    #end

  end

  # GET /players/1/edit
  def edit
   #@tryout = Tryout.find(params[:tryout_id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)
    respond_to do |format|
      if @player.save
        format.html { redirect_to confirm_tryout_path(params[:tryout_id]), notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)

        format.html { redirect_to tryouts_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def player_params
    params.require(:player).permit(:type)
  end

  ### block player users from doing stuff!!
      def permissions
    redirect_to tryouts_path if (profile_signed_in? == false) || (current_profile.type != "Coach")
      end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
    <% if @player.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

          <ul>
            <% @player.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
    <% end %>
    <div class="row">
      <div class="col-md-6">
        <h3><u>Player Information</u>:</h3>
            <div class="field">
              <%= f.label :type %><br>
              <%= f.select(:type, ['Player', 'Coach'], class:'form-control') %>
            </div>
        <p>
          <strong>First Name:</strong>
          <%= @player.first_name %>
        </p>

        <p>
          <strong>Last Name:</strong>
          <%= @player.last_name %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @player.email %>
        </p>

        <p>
          <strong>Phone:</strong>
          <%= @player.phone %>
        </p>


      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-12">
        <div class="actions">
          <%= f.submit 'Submit', class: 'btn btn-primary pull-right' %>
        </div>
      </div>
    </div>
<% end %>

app/views/players/edit.html.erb
<% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% @player.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Edit Player Information</h1>
  </div>
  <div class="panel-body">
    <%= render 'form' %>

app/views/players/index.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h1>Players</h1>
  </div>
  <div class="panel-body">
    <table class="table table-hover table-striped table-responsive">
      <thead>
      <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Gender</th>
        <th>Date of Birth</th>
        <th>Experience</th>
        <th colspan="1"></th>
      </tr>
      </thead>

      <tbody>
      <% @players.each do |player| %>
          <tr>
	          <td><%= player.id %></td>
            <td><%= player.type %></td>
            <td><%= link_to player.first_name.to_s + ' ' + player.last_name.to_s, player_path(player) %></td>
            <td><%= player.email %></td>
            <td><%= player.phone %></td>
            <td><%= player.gender %></td>
            <td><%= player.dob%></td>
            <td><%= player.experience %></td>
            <td><%= link_to 'Details', player_path(player), class: 'btn btn-default' %></td>
            <td><%= link_to 'Make Coach', edit_player_path(player), class: 'btn btn-info' %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>


  </div>
</div>

app/views/players/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h1>New Player <%= link_to 'Back', players_path, class:'btn btn-success pull-right' %></h1>
    </div>
    <div class="panel-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/players/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3>Player Information: <u><b><%= @player.first_name + ' ' + @player.last_name%></b></u></h3>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-6">
        <p>
          <strong>id:</strong>
          <%= @player.id %>
        </p>

        <p>
          <strong>Type:</strong>
          <%= @player.type %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @player.email %>
        </p>

        <p>
          <strong>Phone:</strong>
          <%= @player.phone %>
        </p>

        <p>
          <strong>Gender:</strong>
          <%= @player.gender %>
        </p>

        <p>
          <strong>Date of Birth:</strong>
          <%= @player.dob.strftime('%m/%d/%Y %I:%M %P') %>
        </p>
      </div>
      <div class="col-md-6">
        <p>
          <strong>Address1:</strong>
          <%= @player.address1 %>
        </p>

        <p>
          <strong>Address2:</strong>
          <%= @player.address2 %>
        </p>

        <p>
          <strong>City:</strong>
          <%= @player.city %>
        </p>

        <p>
          <strong>State:</strong>
          <%= @player.state %>
        </p>

        <p>
          <strong>Zip:</strong>
          <%= @player.zip %>
        </p>


      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-12">
          <h4><strong>Experience:</strong></h4>
          <%= @player.experience %>
      </div>
    </div>
  </div>
</div>