config/routes.rb
Rails.application.routes.draw do
  resources :payment_notifications

  devise_for :profiles, controllers: {
        sessions: 'profiles/sessions'
      }

  root 'tryouts#index'

get 'confirm' => 'tryouts#confirm', as: :tryouts_confirm

resources :tryouts do
  resources :players
end

resources :coaches do
  resources :evaluations
end
  resources :guardianships
  resources :evaluations
  resources :guardians
  resources :coaches
  resources :players

  resources :tryouts do
    member do
get 'confirm' => 'tryouts#confirm'

    end
 end

  resources :tryouts do
    resources :player_tryouts
  end

  resources :player_tryouts do
    resources :players
  end

  resources :player_tryouts

end

app/models/coach.rb
class Coach < Profile
  has_many :evaluations
end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
  belongs_to :coach
  belongs_to :player_tryout
end

app/models/guardian.rb
class Guardian < ActiveRecord::Base
  has_many :guardianships
  belongs_to :profile
end

app/models/guardianship.rb
class Guardianship < ActiveRecord::Base
  belongs_to :guardian
  belongs_to :player
end

app/models/payment_notification.rb
class PaymentNotification < ActiveRecord::Base
	belongs_to :player_tryout
end

app/models/player.rb
class Player < Profile
  has_many :player_tryouts#, dependent: :destroy
  has_many :guardianships
end

app/models/player_tryout.rb
class PlayerTryout < ActiveRecord::Base
  belongs_to :player
  belongs_to :tryout
  has_many   :evaluations
  has_one    :payment_notification
end
#serialize :params, Hash
def paypal_url(pt_id,payment_amt)
  values = {
  	:business => 'aesotericon-facilitator@gmail.com',
    :cmd => '_xclick',
    :amount => payment_amt,
    :item_name => 'Soccer Tryout Registration',
    :return => 'http://cryptic-mesa-7823.herokuapp.com',
    :cancel_return => 'http://cryptic-mesa-7823.herokuapp.com/',
    :custom => pt_id,
    :notify_url => 'http://cryptic-mesa-7823.herokuapp.com/payment_notifications'
  }
  "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable
 #has_one :guardian


        after_create :create_player
        def create_player
          @user = Profile.find(id)
          @user.type="Player"
          @user.save

        end

        # This method associates the attribute ":avatar" with a file attachment
          has_attached_file :photo, :path => "/:attachment/:style/:filename",styles: {
            thumb: '100x100>',
            square: '200x200#',
            medium: '300x300>'
          }, :default_url => "https://s3.amazonaws.com/alan.idi/photos/medium/missing.png"

          # Validate the attached image is image/jpg, image/png, etc
          validates_attachment_content_type :photo, :content_type => /\Aimage\/.*\Z/

end

app/models/tryout.rb
class Tryout < ActiveRecord::Base
  has_many :player_tryouts
end

app/controllers/coaches_controller.rb
class CoachesController < ApplicationController
  before_action :set_coach, only: [:show, :edit, :destroy, :update]
  ### block player users from doing stuff!!
  before_action :permissions#, except: [:index]#, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  # GET /coaches
  # GET /coaches.json
  def index
    @coaches = Coach.all
  end

  # GET /coaches/1
  # GET /coaches/1.json
  def show
  end

  # GET /coaches/new
  def new
    @coach = Coach.new
  end

  # GET /coaches/1/edit
  def edit
  end

  # POST /coaches
  # POST /coaches.json
  def create
    @coach = Coach.new(coach_params)

    respond_to do |format|
      if @coach.save
        format.html { redirect_to @coach, notice: 'Coach was successfully created.' }
        format.json { render :show, status: :created, location: @coach }
      else
        format.html { render :new }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coaches/1
  # PATCH/PUT /coaches/1.json
  def update
    respond_to do |format|
      if @coach.update(coach_params)
        format.html { redirect_to tryouts_path, notice: 'Coach was successfully updated.' }
        format.json { render :show, status: :ok, location: @coach }
      else
        format.html { render :edit }
        format.json { render json: @coach.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coaches/1
  # DELETE /coaches/1.json
  def destroy
    @coach.destroy
    respond_to do |format|
      format.html { redirect_to coaches_url, notice: 'Coach was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coach
      @coach = Coach.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coach_params
      params.require(:coach).permit(:type, :first_name, :last_name, :email, :phone, :profile_id)
    end
### block player users from doing stuff!!
    def permissions
  redirect_to tryouts_path if (profile_signed_in? == false) || (current_profile.type != "Coach")
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show,:edit, :destroy,:update]
  before_action :permissions, except: [:new]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new

  #  if Player.exists?(:profile_id => current_profile.id)
      #do nothing for now
      @tryout = Tryout.find(params[:tryout_id])
      @player = Player.find(current_profile.id)
      #redirect_to edit_tryout_player_path(@tryout.id, @player.id), notice: 'Player exists'
      redirect_to confirm_tryout_path(@tryout.id), notice: 'Player exists'

  #  else
  #    @player = Player.new
  #    @player.assign_attributes(:profile_id => current_profile.id)
     # @player.save
    #  @tryout = Tryout.find(params[:tryout_id])
    #end

  end

  # GET /players/1/edit
  def edit
   #@tryout = Tryout.find(params[:tryout_id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)
    respond_to do |format|
      if @player.save
        format.html { redirect_to confirm_tryout_path(params[:tryout_id]), notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)

        format.html { redirect_to tryouts_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = Player.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def player_params
    params.require(:player).permit(:type)
  end

  ### block player users from doing stuff!!
      def permissions
    redirect_to tryouts_path if (profile_signed_in? == false) || (current_profile.type != "Coach")
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/guardians_helper.rb
module GuardiansHelper
end

app/helpers/guardianships_helper.rb
module GuardianshipsHelper
end

app/helpers/player_tryouts_helper.rb
module PlayerTryoutsHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/tryouts_helper.rb
module TryoutsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Soccer Tryout Manager</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <!--<link href="bootstrap.css" rel="stylesheet">
  <link href="heroic-features.css" rel="stylesheet">-->
</head>

<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation" style="background-color:#336699">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Soccer Tryout Manager", tryouts_path, {:class => "navbar-brand", :style => "color:white"} %>
      <ul class="nav navbar-nav navbar-left">
        <% if (profile_signed_in? && current_profile.type == 'Coach') %>
            <li><%= link_to 'Players', players_path, class: 'navbar-link' %></li>
            <li><%= link_to 'Coaches', coaches_path, class: 'navbar-link' %></li>
        <% elsif (profile_signed_in? && current_profile.type == 'Player') %>
            <li><%= link_to 'Upcoming Tryouts', '#', class: 'navbar-link' %></li>
        <% end %>
      </ul>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if profile_signed_in? %>
            <li><a class='navbar-link' style='color:white'> Greetings! <b><%=current_profile.first_name%></b></a></li>
            <li><%= link_to 'Edit Profile', edit_profile_registration_path, class: 'navbar-link', style: 'color:white' %></li>
            <li><%= link_to 'Logout', destroy_profile_session_path, method: :delete, :class => 'navbar-link', :style => 'color:white' %></li>
        <% else %>
            <li><%= link_to "Sign up", new_profile_registration_path, :class => 'navbar-link', :style => 'color:white' %></li>
            <li><%= link_to 'Log in', new_profile_session_path, :class => 'navbar-link', :style => 'color:white' %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <div class="row">
    <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </div>
  <div class="row">
    <%= yield %>
  </div>
  <div class="navbar navbar-default navbar-fixed-bottom" style="background-color:#336699">
    <div class="container" style="padding-top: 10px">
      <p class="text-center" style="color: #9d9d9d;">Copyright &copy;
        <a style="color: #fff;" href="mailto:heileman@unm.edu?Subject=ECE%20595%20-%20Soccer%20Tryout%20Manager" target="_blank">
          <b><u>University of New Mexico</u></b></a> - Soccer Tryout Manager 2015</p>
    </div>
  </div>
</div>
<!--<script src="js/jquery.js"></script>
<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>-->
</body>
</html>